int cat_x = 900;
int cat_y = 500;
int yellowmouse_x = 160;
int yellowmouse_y = 400;
int purplemouse_x = 520;
int purplemouse_y = 360;
int greenmouse_x = 960;
int greenmouse_y = 320;
int pinkmouse_x = 360;
int pinkmouse_y = 610;
int orangemouse_x = 700;
int orangemouse_y = 580;
PImage backgroundImage;
String imagePath = "img/forest.jpg";
public boolean drawnBackgroundIsShowing = true;
public final int F_KEY = 70;
public final int S_KEY = 83;
final int SPACING = 100;
final int BLOCK_SIZE = 100;
PImage mouse1;
PImage mouse2;
PImage mouse3;
PImage mouse4;
PImage mouse5;
